const assert = require('node:assert/strict');
const C = require('../schedule-core.js');
assert.deepEqual(C.range('weekly','2026-01-01'), ['2025-12-29','2026-01-04']);
assert.equal(C.range('monthly','2024-02-02')[1], '2024-02-29');
assert.throws(() => C.dateObject('2026-02-30'));
assert.throws(() => C.dateObject('0001-01-01'));
assert.throws(() => C.quickInput('13/40 09:00 잘못된 날짜', '2026-10-02'));
assert.equal(C.escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');
const first = C.newEvent('2026-09-25');
first.title = '행사'; first.time = '09:00'; first.notes = '내부 메모'; first.checklist = [{id:'a',text:'준비',done:true}];
const snapshot = C.empty(); snapshot.events.push(first);
const result = C.copyWeek(snapshot, [first.id], '2026-10-02', true);
assert.equal(result.added.length, 1);
assert.equal(result.added[0].date, '2026-10-02');
assert.equal(result.added[0].status, 'tentative');
assert.equal(result.added[0].checklist[0].done, false);
snapshot.events.push(result.added[0]);
assert.equal(C.copyWeek(snapshot, [first.id], '2026-10-02', true).added.length, 0);
assert.equal(C.copyWeek(C.empty(), [], '2026-10-02', false).added.length, 0);
assert.equal(C.noteText(first).includes('내부 메모'), true);
const busy = {...first, endTime:'10:00'};
const point = {...first,id:'point',time:'09:30',endTime:''};
assert.equal(C.conflicts([busy],point).length,1);
assert.equal(C.conflicts([busy],{...point,time:'10:00'}).length,0);
console.log('JavaScript date, validation, escaping, copy and checklist checks passed.');
